---
- name: "Create Airsonic Directories"
  file:
    path: "{{ item }}"
    state: "directory"
    # mode: 0755
  with_items:
    - "{{ airsonic_data_directory }}/data"
    - "{{ airsonic_data_directory }}/playlists"

- name: "Airsonic Docker Container"
  docker_container:
    name: "airsonic"
    image: "{{ airsonic_image }}"
    pull: "true"
    volumes:
      - "{{ airsonic_data_directory }}/data:/airsonic/data:rw"
      - "{{ airsonic_data_directory }}/playlists:/airsonic/playlists:rw"
      - "{{ music_root }}:/airsonic/music:rw"
      - "{{ podcasts_root }}:/airsonic/podcasts:rw"
      - "{{ audiobooks_root }}:/airsonic/audiobooks:rw"
    ports:
      - "{{ airsonic_port }}:4040"
    restart_policy: "unless-stopped"
    memory: "1g"
    labels:
      traefik.backend: "airsonic"
      traefik.frontend.rule: "Host:{{ airsonic_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ airsonic_available_externally }}"
      traefik.port: "{{ airsonic_port }}"