---
- name: Create Airsonic Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ airsonic_data_directory }}/data"
    - "{{ airsonic_data_directory }}/playlists"

- name: Airsonic Docker Container
  docker_container:
    name: airsonic
    image: "{{ airsonic_image }}"
    pull: true
    volumes:
      - "{{ airsonic_data_directory }}/data:/airsonic/data:rw"
      - "{{ airsonic_data_directory }}/playlists:/airsonic/playlists:rw"
      - "{{ airsonic_music_directory }}:/airsonic/music:rw"
      - "{{ airsonic_podcasts_directory }}:/airsonic/podcasts:rw"
    ports:
      - "{{ airsonic_port }}:4040"
    restart_policy: "{{ airsonic_restart_policy }}"
    memory: "{{ airsonic_memory_limit }}"
    labels:
      traefik.backend: "airsonic"
      traefik.frontend.rule: "Host:{{ airsonic_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ airsonic_available_externally }}"
      traefik.port: "{{ airsonic_port }}"

