- name: "Autoheal Docker Container"
  docker_container:
    name: "autoheal"
    image: "{{ autoheal_image }}"
    pull: "true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      AUTOHEAL_CONTAINER_LABEL: "all"
      AUTOHEAL_INTERVAL: "{{ autoheal_interval }}"
      AUTOHEAL_START_PERIOD: "{{ autoheal_start_after }}"
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: "{{ autoheal_kill_wait }}"
    restart_policy: "{{ autoheal_restart_policy }}"
    memory: "{{ autoheal_memory_limit }}"