---
- name: Create Bazarr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bazarr_data_directory }}"

- name: Bazarr
  docker_container:
    name: bazarr
    image: "{{ bazarr_image }}"
    pull: true
    volumes:
      - "{{ bazarr_tv_directory }}:/tv:rw"
      - "{{ bazarr_movies_directory }}:/movies:rw"
      - "{{ bazarr_data_directory }}:/config:rw"
    ports:
      - "{{ bazarr_port }}:6767"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ bazarr_user_id }}"
      PGID: "{{ bazarr_group_id }}"
    restart_policy: "{{ bazarr_restart_policy }}"
    memory: "{{ bazarr_memory_limit }}"
    labels:
      traefik.backend: "bazarr"
      traefik.frontend.rule: "Host:{{ bazarr_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ bazarr_available_externally }}"
      traefik.port: "{{ bazarr_port }}"