- name: Cloudflare Dynamic DNS Container
  docker_container:
    name: cloudflare-ddns
    image: "{{ cloudflare_image }}"
    pull: true
    env:
      ZONE: "{{ cloudflare_zone }}"
      HOST: "{{ cloudflare_host }}"
      EMAIL: "{{ cloudflare_email }}"
      API: "{{ cloudflare_api_key }}"
      PROXY: "false"
    restart_policy: "{{ cloudflare_restart_policy }}"
    memory: "{{ cloudflare_memory_limit }}"

