---
- name: "Create Duplicati Directory"
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ duplicati_data_directory }}"

- name: "Dupicati Docker Container"
  docker_container:
    name: "duplicati"
    image: "{{ duplicati_image }}"
    pull: "true"
    ports:
      - "{{ duplicati_port }}:8200"
    env:
      PUID: "{{ duplicati_user_id }}"
      PGID: "{{ duplicati_group_id }}"
    volumes:
      - "{{ duplicati_data_directory }}:/config:rw"
      - "{{ samba_shares_root }}:/source/shares:rw"
      - "{{ docker_home }}:/source/docker:rw"
      - "/etc/timezone:/etc/timezone:ro"
    restart_policy: "unless-stopped"
    memory: "1g"
    labels:
      traefik.backend: "duplicati"
      traefik.frontend.rule: "Host:{{ duplicati_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ duplicati_available_externally }}"
      traefik.port: "{{ duplicati_port }}"
