- name: Create get_iplayer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ get_iplayer_config_directory }}"
    - "{{ get_iplayer_download_directory }}"

- name: get_iplayer Docker Container
  docker_container:
    name: get_iplayer
    image: "{{ get_iplayer_image }}"
    pull: true
    volumes:
      - "{{ get_iplayer_config_directory }}:/root/.get_iplayer:rw"
      - "{{ get_iplayer_download_directory }}:/root/output:rw"
    ports:
      - "{{ get_iplayer_port }}:8181"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "get_iplayer"
      traefik.frontend.rule: "Host:{{ get_iplayer_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ get_iplayer_available_externally }}"
      traefik.port: "{{ get_iplayer_port }}"
