---
- name: Create Guacamole directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ guacamole_data_directory }}/config"

- name: Copy Guacamole database init script
  copy:
    src: "files/guacamole/initdb-0.9.14.sql"
    dest: "{{ guacamole_data_directory }}/initdb-0.9.14.sql"

- name: Remove Old Guacamole Mysql Docker Container
  docker_container:
    name: guacamole-mysql
    state: absent
    keep_volumes: true

- name: Remove Old Guacamole guacd Docker Container
  docker_container:
    name: guacamole-guacd
    state: absent
    keep_volumes: true

- name: Remove old Guacamole directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ guacamole_data_directory }}/mysql"

# docker run -v /home/david/.guac:/config:rw  -p 8080:8080   oznu/guacamole

- name: Guacamole Container
  docker_container:
    name: guacamole
    image: "oznu/guacamole"
    pull: true
    volumes:
      - "{{ guacamole_data_directory }}/config:/config:rw"
    ports:
      - "{{ guacamole_port }}:8080"
    env:
      MYSQL_DATABASE: "guacamole"
      MYSQL_USER: "guacamole-user"
      MYSQL_PASSWORD: "guacamole-pass"
    restart_policy: "{{ guacamole_restart_policy }}"
    memory: "{{ guacamole_memory_limit }}"
    labels:
      traefik.backend: "guacamole"
      traefik.frontend.rule: "Host:{{ guacamole_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ guacamole_available_externally }}"
      traefik.port: "8080"

- name: Restart Guacamole Container
  docker_container:
    name: guacamole
    image: "oznu/guacamole"
    restart: true