---
- name: Create jackett Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ jackett_data_directory }}"

- name: jackett
  docker_container:
    name: jackett
    image: "{{ jackett_image }}"
    volumes:
      - "{{ jackett_data_directory }}:/config:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ jackett_torrents_root }}:/downloads"
    ports:
      - "{{ jackett_port }}:9117"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: "{{ jackett_restart_policy }}"
    memory: "{{ jackett_memory_limit }}"
    labels:
      traefik.backend: "jackett"
      traefik.frontend.rule: "Host:{{ jackett_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ jackett_available_externally }}"
      traefik.port: "9117"