- name: Create Tautulli Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ tautulli_config_directory }}"

- name: Tautulli Docker Container
  docker_container:
    name: tautulli
    image: linuxserver/tautulli
    pull: true
    volumes:
      - "{{ tautulli_config_directory }}:/config:rw"
    network_mode: "host"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ tautulli_user_id }}"
      PGID: "{{ tautulli_group_id }}"
    restart_policy: "{{ tautulli_restart_policy }}"
    memory: "{{ tautulli_memory_limit }}"
    labels:
      traefik.backend: "tautulli"
      traefik.frontend.rule: "Host:tautulli.{{ ansible_nas_domain }}"
      traefik.enable: "{{ tautulli_available_externally }}"
      traefik.port: "8181"