---
- name: Watchtower Docker Container
  docker_container:
    name: watchtower
    image: "{{ watchtower_image }}"
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    command: "{{ watchtower_command }}"
    restart_policy: "{{ watchtower_restart_policy }}}"
    memory: "{{ watchtower_memory_limit }}"